
CREATE TABLE User(
userid NUMBER(11) NOT NULL,
fbid VARCHAR(255),
lastlogin DATE,
created DATE,
CONSTRAINT User_PRIMARY_KEY PRIMARY KEY (id))

CREATE TABLE List(
listid NUMBER(11) NOT NULL,
userid NUMBER(11) NOT NULL FOREIGN KEY,
name VARCHAR(255),
created DATE,
updated DATE,
CONSTRAINT User_PRIMARY_KEY PRIMARY KEY (listid))

CREATE TABLE item(
itemid NUMBER(11) NOT NULL,
listid NUMBER(11) NOT NULL FOREIGN KEY,
name VARCHAR(255),
created DATE,
updated DATE,
CONSTRAINT User_PRIMARY_KEY PRIMARY KEY (itemid))

CREATE TABLE List_Users(
userid NUMBER(11) NOT NULL FOREIGN KEY,
listid NUMBER(11) NOT NULL FOREIGN KEY)

commit;